volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    volumes:
      - static:/backend_static/
    env_file: .env
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/frontend_static/
    command: cp -r /app/build/. /frontend_static/
  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
